replicaCount: 1

frontend:
  image:
    repository: panjek266/apps-fe
    tag: v0.0.3
  service:
    type: LoadBalancer
    port: 80
  config:
    backendHost: backend-svc
    backendPort: 8080

backend:
  image:
    repository: panjek266/python-be
    tag: v0.0.1
  service:
    type: ClusterIP
    port: 8080
    targetPort: 5001

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 50
  memoryUtilization: 50

resources: {}
