frontend:
  image:
    repository: panjek266/apps-fe
    tag: v0.0.3-prod
  service:
    type: LoadBalancer
    port: 80
  config:
    backendHost: backend-svc
    backendPort: 8080

backend:
  image:
    repository: panjek266/python-be
    tag: v0.0.1-prod
  service:
    type: ClusterIP
    port: 8080
    targetPort: 5001

hpa:
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 50

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
