apiVersion: v1
kind: Service
metadata:
  name: {{ include "tripla-apps.fullname" . }}-backend-svc
  labels:
    {{- include "tripla-apps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
