apiVersion: v1
kind: Service
metadata:
  name: {{ include "tripla-apps.fullname" . }}-frontend-svc
  labels:
    {{- include "tripla-apps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
